Repository openshift/image-customization-controller, pull requests merged in 2022-01, with the labels that each got.

#22 Bug 2037288: Eliminate unsafe default for ironic agent image
  cmd/static-server/main_test.go
  pkg/env/env.go
  pkg/ignition/builder.go
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#28 Bug 2038272: Improve error reporting
  cmd/controller/main.go
  cmd/static-server/main.go
  go.mod
  go.sum
  pkg/env/env.go
  pkg/ignition/builder.go
  pkg/ignition/builder_test.go
  pkg/imagehandler/imagehandler.go
  pkg/imagehandler/imagehandler_test.go
  pkg/imageprovider/rhcos.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/firmwareschema_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/hostfirmwaresettings_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/metal3-io/baremetal-operator/controllers/metal3.io/action_result.go
  vendor/github.com/metal3-io/baremetal-operator/controllers/metal3.io/baremetalhost_controller.go
  vendor/github.com/metal3-io/baremetal-operator/controllers/metal3.io/hostfirmwaresettings_controller.go
  vendor/github.com/metal3-io/baremetal-operator/controllers/metal3.io/preprovisioningimage_controller.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/irmc.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/imageprovider/default.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/imageprovider/invalid.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#30 Bug 2039227: Fetch secret from mounted file when env var is not specified
  cmd/static-server/main.go
  cmd/static-server/main_test.go
  test/data/nm0.yaml
  test/data/nm1.yaml
  test/data/nm2.yaml
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#31 Bug 2034527: Add IP_OPTIONS environment variable
  cmd/static-server/main.go
  pkg/env/env.go
  pkg/ignition/builder.go
  pkg/ignition/builder_test.go
  pkg/ignition/service_config.go
  pkg/ignition/service_config_test.go
  pkg/imageprovider/rhcos.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#33 Bug 2045927: Add proxy for ironic-agent.service
  cmd/static-server/main.go
  pkg/env/env.go
  pkg/ignition/builder.go
  pkg/ignition/builder_test.go
  pkg/ignition/service_config.go
  pkg/ignition/service_config_test.go
  pkg/imageprovider/rhcos.go
Labels: ok-to-test, lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#35 Bug 2041183: Configure hostnames via ignition
  cmd/static-server/main.go
  pkg/ignition/builder.go
  pkg/ignition/builder_test.go
  pkg/imageprovider/rhcos.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug
