Repository openshift/image-customization-controller, pull requests merged in 2023-12, with the labels that each got.

#109 OCPBUGS-15599: configurable ironic agent vlan creation
  README.md
  cmd/static-server/main.go
  pkg/env/env.go
  pkg/ignition/builder.go
  pkg/ignition/builder_test.go
  pkg/ignition/service_config.go
  pkg/ignition/service_config_test.go
  pkg/imageprovider/rhcos.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#102 [release-4.10] OCPBUGS-21766: Watch networkData Secrets for changes
  cmd/controller/main.go
  go.mod
  go.sum
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_validation.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_validation.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/bmceventsubscription_webhook.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/firmwareschema_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/metal3-io/baremetal-operator/controllers/metal3.io/baremetalhost_controller.go
  vendor/github.com/metal3-io/baremetal-operator/controllers/metal3.io/bmceventsubscription_controller.go
  vendor/github.com/metal3-io/baremetal-operator/controllers/metal3.io/host_config_data.go
  vendor/github.com/metal3-io/baremetal-operator/controllers/metal3.io/host_state_machine.go
  vendor/github.com/metal3-io/baremetal-operator/controllers/metal3.io/hostfirmwaresettings_controller.go
  vendor/github.com/metal3-io/baremetal-operator/controllers/metal3.io/preprovisioningimage_controller.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/irmc.go
  vendor/github.com/metal3-io/baremetal-operator/pkg/provisioner/provisioner.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#115 METAL-835: Get secret from mounted file when envvar empty
  cmd/controller/main.go
Labels: lgtm, approved, jira/valid-reference
