Repository openshift/image-customization-controller, pull requests merged in 2023-07, with the labels that each got.

#87 OCPBUGS-9072: Pass BareMetalHost name to IPA
  pkg/ignition/builder.go
  pkg/ignition/builder_test.go
  pkg/ignition/service_config.go
  pkg/ignition/service_config_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#92 OCPBUGS-15909: Revert: Pass BareMetalHost name to IPA"
  pkg/ignition/builder.go
  pkg/ignition/builder_test.go
  pkg/ignition/service_config.go
  pkg/ignition/service_config_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#93 OCPBUGS-9072: Pass BareMetalHost name to IPA (take 2)
  pkg/ignition/service_config.go
  pkg/ignition/service_config_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference
