Repository openshift/image-customization-controller, pull requests merged in 2024-01, with the labels that each got.

#110 METAL-834: Add --metrics-addr argument to controller
  cmd/controller/main.go
Labels: lgtm, approved, jira/valid-reference

#111 OCPBUGS-24576: configurable ironic agent vlan creation
  README.md
  cmd/static-server/main.go
  pkg/env/env.go
  pkg/ignition/builder.go
  pkg/ignition/builder_test.go
  pkg/ignition/service_config.go
  pkg/ignition/service_config_test.go
  pkg/imageprovider/rhcos.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#120 OCPBUGS-24579: account for more cases when handling base URLs
  pkg/ignition/service_config.go
  pkg/ignition/service_config_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference
